name: macOS_test

on: workflow_dispatch

jobs:
  build-macos:
    strategy:
      matrix:
        os: [macos-13, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    #- name: Checkout source
    #  run: git clone https://github.com/cfyzium/bearlibterminal
    - name: Look around
      shell: bash
      run: |
        cmake --version || true
        cmake -G || true
        gcc --version || true
        pwd
        ls -lh
        system_profiler SPDisplaysDataType
        open ~/
        screencapture screenshot.png
        #mkdir build
        #cd build
        #cmake ../bearlibterminal
        #ls -lh
        #make
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-screenshot
        path: ${{ github.workspace }}/screenshot.png
