name: CI

on: [push, workflow_dispatch]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    #container: ${{ matrix.container }}
    #strategy:
    #  matrix:
    #    container: [quay.io/pypa/manylinux1_x86_64, quay.io/pypa/manylinux2014_i686]
    #container: quay.io/pypa/manylinux1_x86_64
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        ls -lh
        echo '---8<---'
        git clone https://github.com/cfyzium/bearlibterminal
        cat << EOF > script.sh
          #!/bin/bash
          mkdir build && cd \$_
          cmake ../workspace/bearlibterminal
          make
        EOF
        chmod a+x ./script.sh
        docker run --rm --mount type=bind,src=`pwd`,dst=/workspace quay.io/pypa/manylinux2014_x86_64 bash -c "workspace/script.sh"
        docker run --rm --mount type=bind,src=`pwd`,dst=/workspace quay.io/pypa/manylinux2014_i686 bash -c "workspace/script.sh"
        tar cvfz artifacts.tgz bearlibterminal/Output/Linux*
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-binaries
        path: ${{ github.workspace }}/artifacts.tgz
    - name: Install MinGW
      run: sudo apt install gcc-mingw-w64 g++-mingw-w64
    - name: Build Windows binaries
      run: |
        cat << EOF > mingw.cmake
          set(CMAKE_SYSTEM_NAME Windows)
          set(CMAKE_C_COMPILER \${MINGW_ARCH}-w64-mingw32-gcc-posix)
          set(CMAKE_CXX_COMPILER \${MINGW_ARCH}-w64-mingw32-g++-posix)
          set(CMAKE_RC_COMPILER \${MINGW_ARCH}-w64-mingw32-windres)
          set(CMAKE_FIND_ROOT_PATH /usr/\${MINGW_ARCH}-w64-mingw32)
          set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
          set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
          set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
        EOF
        cat << EOF > script.sh
          #!/bin/bash
          rm -rf build && mkdir build && cd \$_
          cmake -DMINGW_ARCH=\$1 -DCMAKE_TOOLCHAIN_FILE=../mingw.cmake ../bearlibterminal
          make
        EOF
        chmod a+x ./script.sh
        ./script.sh x86_64
        ./script.sh i686
    - name: Upload MinGW artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mingw-binaries
        path: ${{ github.workspace }}/bearlibterminal/Output/Windows*
