name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    #container: ${{ matrix.container }}
    #strategy:
    #  matrix:
    #    container: [quay.io/pypa/manylinux1_x86_64, quay.io/pypa/manylinux2014_i686]
    #container: quay.io/pypa/manylinux1_x86_64
    steps:
    - name: Run a multi-line script
      run: |
        echo ${{ github.workspace }}
        pwd
        ls -lh
        echo '---8<---'
        git clone https://github.com/cfyzium/bearlibterminal
        cat << EOF > script.sh
        rm -rf build
        mkdir build
        cd build
        cmake ../bearlibterminal
        make
        EOF
        chmod a+x ./script.sh
        docker run --rm --mount type=bind,src=`pwd`,dst=/workspace quay.io/pypa/manylinux2014_x86_64 bash -c "cd /workspace; ./script.sh"
        docker run --rm --mount type=bind,src=`pwd`,dst=/workspace quay.io/pypa/manylinux2014_i686 bash -c "cd /workspace; ./script.sh"
        tar cvfz artifacts.tgz bearlibterminal/Output
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifact-xyz
        path: ${{ github.workspace }}/artifacts.tgz
